version: 1.0.{build}

before_build:
- ps: nuget restore ./Cinema/Cinema.sln

build:
  project: ./Cinema/Cinema.sln
  verbosity: minimal

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 3ike6uVm+8Eh8v5tlC6EIhwIFOq1Ha6okfpWvuoMXnBtIeETtdrYKI2VWPQD+n/1

after_test: 
    - Cinema\packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"Cinema\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  Cinema.Tests\bin\debug\Cinema.Tests.dll" -output:coverage.xml

    - Cinema\packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover coverage.xml